### ISSUE TITLE
自定义动作导出csv在应用simplepro后报错

### ISSUE THREAD

**Issue by cpu8802667** [newpanjing/simplepro#11]
def export_to_csv(modeladmin, request, queryset):
    opts = modeladmin.model._meta
    response = HttpResponse(content_type="text/csv;chartset=utf_8_sig")
    response['Content-Disposition'] = "attachment;filename={}.csv".format(opts.app_label)
    # print(response['Content-Disposition'])
    response.write(codecs.BOM_UTF8)
    writer = csv.writer(response)
    fields = [field for field in opts.get_fields() if not field.many_to_many and not field.one_to_many]
    # print(opts.verbose_name)
    writer.writerow([field.verbose_name for field in fields])
    for obj in queryset:
        data_row = []
        for field in fields:
            value = getattr(obj, field.name)

            if isinstance(value, datetime.datetime):
                value = value.strftime('%d/%m/%Y')
            data_row.append(value)
        writer.writerow(data_row)

    return response
class deviceAdmin(admin.ModelAdmin):
        actions = [accept,reject,export_to_csv]
![image](https://user-images.githubusercontent.com/53026387/67565117-3b436a00-f757-11e9-92df-23827a9c2d8c.png)

**Comment by newpanjing** [comment]
目前这个是ajax请求的，ajax不支持直接响应文件，建议用链接按钮的形式来实现。
