### ISSUE TITLE
get_queryset

### ISSUE THREAD

**Issue by CinFree** [newpanjing/simplepro#13]
重写get_queryset，这个会执行3遍

**Comment by newpanjing** [comment]
能不能详细描述下？目前我这边测试到的只会一次。

**Comment by CinFree** [comment]
def get_queryset(self, request):

    qs = super().get_queryset(request)
    print('get_querysetget_queryset')

    return qs.filter(id__gte=1)
把print放前面或后面都是一样的。页面全局刷新的时候会打印3次，只点击刷新按钮会打印2次
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jingle"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月16日(星期六) 下午2:42
收件人:&nbsp;"newpanjing/simplepro"<simplepro@noreply.github.com&gt;;
抄送:&nbsp;"△~：淩晨ヾ."<78203731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [newpanjing/simplepro] get_queryset (#13)




能不能详细描述下？目前我这边测试到的只会一次。
