### ISSUE TITLE
自定义Action 默认是不可点击状态

### ISSUE THREAD

**Issue by CinFree** [newpanjing/simplepro#14]
自定义Action 默认是不可点击状态

**Comment by newpanjing** [comment]
自定义按钮增加了个属性enable

def aa():
  ...

aa.enable=True
aa.enable=False

请更新至simplepro 1.0

**Comment by CinFree** [comment]
> 自定义按钮增加了个属性enable
> 
> def aa():
> ...
> 
> aa.enable=True
> aa.enable=False
> 
> 请更新至simplepro 1.0

ojbk
