### ISSUE TITLE
simplepro license的问题

### ISSUE THREAD

**Issue by hutong236** [newpanjing/simplepro#18]
环境：
```
C:\Users\hutong>pip list|find "django"
django-import-export   2.0.2
django-simpleui        3.9.1

C:\Users\hutong>pip list|find "simple"
django-simpleui        3.9.1
simplepro              1.3
```

我的源码放在D:\hutong\xxx\xxxv2_work 启动django的bat文件，放到桌面上。 
```
cat run.bat
 python D:\hutong\xxx\xxxv2_work\manage.py runserver
```

激活后，simplepro.lic文件存储到桌面上了。 我再次把run.bat复制到 D:\hutong\xxx\xxxv2_work 执行，又需要激活？ 不知道这是不是有问题？ 每次在同一台电脑，变动位置都需要重新激活？或是重装了系统也要重新激活，激活又只能激活3次，好麻烦的，只能找你们处理。

**Comment by newpanjing** [comment]
同一台电脑重复激活 只占用一次激活数

发自我的iPhone
