### ISSUE TITLE
没有对model表进行config的模型在pro里面没办法查看

### ISSUE THREAD

**Issue by Abraverman666** [newpanjing/simplepro#2]
model表没有设置  
‘’‘
 list_display = ("dormitory_title", "building_title", "number", "sum_student", "time")
    readonly_fields = ("time", )
    list_filter = ("building__dormitory__title", "building__title", "sum_student")
    search_fields = ("number",)
‘’’

这些东西的时候 没办法使用pro

**Comment by newpanjing** [comment]
请升级至0.9b，已经修复该问题。
```
pip instlal simplepro -U -i https://pypi.python.org/simple
```
