### ISSUE TITLE
新版本建议

### ISSUE THREAD

**Issue by irabbit666** [newpanjing/simplepro#22]
1. 增加列表页每一行的自定义按钮，进行自定一个操作。（编辑、删除实在不够啊）
2. 导入时自动过滤去重，自动将数字格式转换为文本格式（否则数字格式会带上.0）,以下是我凑合修改现在自己在用的代码：

`    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        # 重写导入，跳过重复，处理文本
        tmp_dict = []
        for row in dataset.dict:
            tmp = OrderedDict()
            for item in row:
                if item == 'username':
                    if '.0' in str(row['username']):
                        row['username'] = str(row['username']).replace('.0', '')
                    # if '.0' in row['username']:
                    #     row['username']=row['username'].replace('.0', '')
                    #
                    if User.objects.filter(username=row['username']).count() > 0:
                        print('跳过++++++++++++++++++++')
                        do_pass = True
                        continue
                    else:
                        do_pass = False
                        tmp[item] = row[item]
                elif not do_pass:
                    tmp[item] = row[item]
            if not do_pass:
                tmp_dict.append(tmp)
        dataset.dict = tmp_dict`

**Comment by newpanjing** [comment]
1. 自定义按钮找已经支持了
2. 导入导出使用的是django-import-export插件，建议反馈到该插件。
