### ISSUE TITLE
license如何计算? 

### ISSUE THREAD

**Issue by twinkle316** [newpanjing/simplepro#25]
1. 我购买了7天试用, 在同一台电脑启动服务, 两次启动端口不同,第二个端口提示需要输入注册码, 恢复试用第一次的端口正常
2. licence对docker每次启动的container都需要重新激活么?

**Comment by newpanjing** [comment]
把docker的用户目录映射的宿主机即可。就不会造成一个docker占用一个激活次数。

**Comment by chengpeng1995** [comment]
> 把docker的用户目录映射的宿主机即可。就不会造成一个docker占用一个激活次数。
有没有具体代码呀，参考一下
