### ISSUE TITLE
后台选择过滤后的全部数据Bug

### ISSUE THREAD

**Issue by xdbytes** [newpanjing/simplepro#26]
![281615537197_ pic](https://user-images.githubusercontent.com/77269893/110912538-05545500-834f-11eb-8f46-618459d4036e.jpg)
数据库总共有几万条数据。如图1、2步我先选择了数据过滤条件，第三步点击了查询，总共查询出40条数据，然后第四步我点击选择全部40条数据，当我进行第五步的时候，正常应该在admin的action方法中传入的queryset只有40条数据，经过我日志打印其实是数据库的所有数据。

**Comment by newpanjing** [comment]
3.0中修复该问题，关注群里更新即可。
