### ISSUE TITLE
自定义的 action 按钮 获取不到queryset

### ISSUE THREAD

**Issue by zhc1208420887** [newpanjing/simplepro#4]
actions = ['make_transfer']

    def make_transfer(self, request, queryset):
        try:
            for i in queryset:
                if i.section == 1:
                    det_obj = DetailCheck.objects.filter(uid=i,section=1)
                    if det_obj:
                        det_obj.update(section=2)
            queryset.update(section=2)
            messages.add_message(request, messages.SUCCESS, '操作成功')
        except Exception:
            messages.add_message(request, messages.ERROR, '操作失败,请重试')

**Comment by newpanjing** [comment]
在1.0版本中已经修复该问题，支持原生的messages
请升级即可。
